name: Metrics

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    branches: ["main", "master"]

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: rndv1
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          base_indepth: yes
          config_timezone: Asia/Yekaterinburg

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          repositories_forks: yes

          filename: github-metrics.svg
